# Generated by Django 5.1.4 on 2024-12-29 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'garages',
                'indexes': [models.Index(fields=['name'], name='garages_name_d89d9d_idx'), models.Index(fields=['city'], name='garages_city_2d2e4c_idx'), models.Index(fields=['location'], name='garages_locatio_9a4b40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=255)),
                ('model', models.CharField(db_index=True, max_length=255)),
                ('production_year', models.IntegerField(db_index=True)),
                ('license_plate', models.CharField(db_index=True, max_length=255)),
                ('garages', models.ManyToManyField(blank=True, related_name='cars', to='backend_logic.garage')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(db_index=True)),
                ('service_type', models.CharField(db_index=True, max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='backend_logic.car')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='backend_logic.garage')),
            ],
            options={
                'db_table': 'maintenances',
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make'], name='cars_make_2a151c_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['model'], name='cars_model_af2c08_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['production_year'], name='cars_product_e96403_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['license_plate'], name='cars_license_e2acb7_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['scheduled_date'], name='maintenance_schedul_06559c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['service_type'], name='maintenance_service_cd0a93_idx'),
        ),
    ]
